"""Prompts domain module initialization."""

from .templates import (
    PROMPT_ROUTER,
    PROMPT_PLANE_EXTRACT,
    PROMPT_GENERAL_BOT,
    PROMPT_QA_RAG,
    PROMPT_WORK_REPORT_EXTRACT,
    PROMPT_TASK_EVALUATION
)

__all__ = [
    "PROMPT_ROUTER",
    "PROMPT_PLANE_EXTRACT",
    "PROMPT_GENERAL_BOT",
    "PROMPT_QA_RAG",
    "PROMPT_WORK_REPORT_EXTRACT",
    "PROMPT_TASK_EVALUATION"
]
